###

GET https://jam-scene-app.herokuapp.com/ads

###

POST https://jam-scene-app.herokuapp.com/ads/search HTTP/1.1
content-type: application/json

  {
    "days": {"sun": true,
            "mon": true,
            "tue": true,
            "wed": true,
            "thu": true,
            "fri": true,
            "sat": true},
    "city": "Seattle",
    "state": "WA",
    "instrument": "Bass"
  }

###

DELETE https://jam-scene-app.herokuapp.com/ad/19

###

POST https://jam-scene-app.herokuapp.com/ads HTTP/1.1
content-type: application/json

  {
    "posted_by": "ca784298-15b9-4049-8b0b-afc9386062a1",
    "city": "Seattle",
    "state": "WA",
    "zip_code": 98121,
    "title": "We're going HARD on Wednesdays.",
    "description":
       "Every Wednesday night, my mom has bowling league. That means that my garage has ROCK... HARD ROCK!!! The gang and I are looking for a HARD ROCKING drummer to round our our HARD ROCKING trio.",
    "avail_mon_am": true,
    "avail_mon_pm": true,
    "avail_tue_am": true,
    "avail_tue_pm": true,
    "avail_wed_am": true,
    "avail_wed_pm": true,
    "avail_thu_am": true,
    "avail_thu_pm": true,
    "avail_fri_am": true,
    "avail_fri_pm": true,
    "avail_sat_am": true,
    "avail_sat_pm": true,
    "avail_sun_am": true,
    "avail_sun_pm": true,
    "post_date": "2022-7-27 16:39:00",
    "instruments": [3]
  }
