GET https://jam-scene-app.herokuapp.com/ads

# DELETE https://jam-scene-app.herokuapp.com/ad/11

# POST https://jam-scene-app.herokuapp.com/ads HTTP/1.1
# content-type: application/json

#   {
#     "posted_by": "bee84a4b-e6ac-42d5-a20f-ee703cd60bfa",
#     "city": "Seattle",
#     "state": "WA",
#     "zipcode": "98106",
#     "title": "Legendary Metal Bassist Needed",
#     "description":
#         "Local metal legends, Bro Magnon, are back with a new album and need touring bassist. If you can shred and own a bass that is black and at least a little bit pointier than most basses, then pack your bags cause we're shows up and down the coast (of Lake Sammamish) all summer.",
#     "avail_mon_am": true,
#     "avail_mon_pm": true,
#     "avail_tue_am": true,
#     "avail_tue_pm": true,
#     "avail_wed_am": true,
#     "avail_wed_pm": true,
#     "avail_thu_am": true,
#     "avail_thu_pm": true,
#     "avail_fri_am": true,
#     "avail_fri_pm": true,
#     "avail_sat_am": true,
#     "avail_sat_pm": true,
#     "avail_sun_am": true,
#     "avail_sun_pm": true,
#     "post_date": "2022-7-22 16:36:00",
#     "instruments": [5]
#   }
