GET https://jam-scene-app.herokuapp.com/conversations/e97ce146-41ce-4d51-b3ca-46566775b131


### 

## "MqEuBlsfIug8Ozfjl2o8IkIyPr43"
## "1bdbaeae-0c1a-42cb-9cba-e737a76f9b36"
POST https://jam-scene-app.herokuapp.com/messages HTTP/1.1
content-type: application/json

  {
    "convoId": "1bdbaeae-0c1a-42cb-9cba-e737a76f9b36+MqEuBlsfIug8Ozfjl2o8IkIyPr43",
    "senderId": "1bdbaeae-0c1a-42cb-9cba-e737a76f9b36",
    "receiverId": "MqEuBlsfIug8Ozfjl2o8IkIyPr43",
    "body": "French horn!",
    "time_sent": "2022-8-01 13:41:00"
  }

###

POST https://jam-scene-app.herokuapp.com/messages HTTP/1.1
content-type: application/json

  {
    "convoId": "1bdbaeae-0c1a-42cb-9cba-e737a76f9b36+MqEuBlsfIug8Ozfjl2o8IkIyPr43",
    "senderId": "1bdbaeae-0c1a-42cb-9cba-e737a76f9b36",
    "receiverId": "MqEuBlsfIug8Ozfjl2o8IkIyPr43",
    "body": "What in gods name would make you think that?",
    "time_sent": "2022-7-27 16:40:00"
  }