GET https://jam-scene-app.herokuapp.com/conversations/e97ce146-41ce-4d51-b3ca-46566775b131


### 

## "MqEuBlsfIug8Ozfjl2o8IkIyPr43"
## "1bdbaeae-0c1a-42cb-9cba-e737a76f9b36"
POST https://jam-scene-app.herokuapp.com/messages HTTP/1.1
content-type: application/json

  {
    "convoId": "MqEuBlsfIug8Ozfjl2o8IkIyPr43+bee84a4b-e6ac-42d5-a20f-ee703cd60bfa",
    "senderId": "bee84a4b-e6ac-42d5-a20f-ee703cd60bfa",
    "receiverId": "MqEuBlsfIug8Ozfjl2o8IkIyPr43",
    "body": "The Gatekeepers",
    "time_sent": "2022-8-01 15:52:00"
  }

###

POST https://jam-scene-app.herokuapp.com/messages HTTP/1.1
content-type: application/json

  {
    "convoId": "MqEuBlsfIug8Ozfjl2o8IkIyPr43+bee84a4b-e6ac-42d5-a20f-ee703cd60bfa",
    "senderId": "MqEuBlsfIug8Ozfjl2o8IkIyPr43",
    "receiverId": "bee84a4b-e6ac-42d5-a20f-ee703cd60bfa",
    "body": "Cool, what's the band called?",
    "time_sent": "2022-8-01 15:52:00"
  }



###

POST https://jam-scene-app.herokuapp.com/messages HTTP/1.1
content-type: application/json

  {
    "convoId": "MqEuBlsfIug8Ozfjl2o8IkIyPr43+bee84a4b-e6ac-42d5-a20f-ee703cd60bfa",
    "senderId": "1bdbaeae-0c1a-42cb-9cba-e737a76f9b36",
    "receiverId": "MqEuBlsfIug8Ozfjl2o8IkIyPr43",
    "body": "The Gatekeepers",
    "time_sent": "2022-7-27 16:40:00"
  }