
GET https://jam-scene-app.herokuapp.com/user/MqEuBlsfIug8Ozfjl2o8IkIyPr43

###

DELETE https://jam-scene-app.herokuapp.com/user/7rgSIhqFaIZFiB0xoN6JpURyqUY2

###

POST https://jam-scene-app.herokuapp.com/users/search HTTP/1.1
content-type: application/json

{
    "zip": "98116",
    "instrument": "Bass",
    "days": {"sun": false, 
            "mon": false, 
            "tue": false,
            "wed": false,
            "thu": false,
            "fri": false,
            "sat": false
            }
}

###

POST https://jam-scene-app.herokuapp.com/users/search HTTP/1.1
content-type: application/json

{
    "zip": "98116",
    "instrument": "Bass",
    "days": {"sun": false, 
            "mon": false, 
            "tue": false,
            "wed": false,
            "thu": false,
            "fri": false,
            "sat": false
            }
}