name: Check and test the source code
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Flutter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'
          channel: 'stable'